services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000' # UI
      - '4317:4317'
      - '4318:4318'
    networks:
      - opentelemetry-vpc

  service-1:
    build: 
      context: ./observer
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    mem_limit: 512m
    networks:
      - opentelemetry-vpc
    depends_on:
      - grafana-lgtm

  service-2:
    build: 
      context: ./observer2
      dockerfile: Dockerfile
    #ports:
    #  - "8081:8080"
    mem_limit: 512m
    networks:
      - opentelemetry-vpc
    depends_on:
      - grafana-lgtm
      

networks:
  opentelemetry-vpc:
    driver: bridge